version: "3.8"

services:

  logstash:
    user: root
    container_name: logstash
    image: logstash:8.11.3
    restart: unless-stopped
    environment:
      xpack.monitoring.elasticsearch.hosts: "[http://elasticsearch:9200]"
      xpack.monitoring.enabled: true
    ports:
      - "9600:9600"
      - "5000:5000"
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - ./docker/logstash/config:/usr/share/logstash/config
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=cluster_1
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_USERNAME=root
      - ELASTIC_PASSWORD=1
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
#      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - elk
#
  kibana:
    image: kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=localhost
#      - ELASTICSEARCH_SSL_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    name: elk
    driver: bridge

volumes:
  es_data: