syntax = "proto3";

package proto.user.v1;

option go_package = "github.com/a-h-pooladvand/microservices/api/user/v1;user";

service UserService {
  rpc CreateUser(CreateUserRequest) returns (UserResponse) {}
  rpc GetUser(GetUserRequest) returns (UserResponse) {}
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {}
  rpc UpdateUser(UpdateUserRequest) returns (UserResponse) {}
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {}
}

message CreateUserRequest {
  string name = 1;
  string surname = 2;
}

message GetUserRequest {
  string id = 1;
}

message ListUsersRequest {
  int32 offset = 1;
  int32 limit = 2;
}

message UpdateUserRequest {
  string id = 1;
  string name = 2;
  string surname = 3;
}

message DeleteUserRequest {
  string id = 1;
}

message UserResponse {
  string id = 1;
  string name = 2;
  string surname = 3;
  string created_at = 4;
  string updated_at = 5;
}

message ListUsersResponse {
  repeated UserResponse users = 1;
}

message DeleteUserResponse {
  bool success = 1;
  string message = 2;
}
