services:
  vault-server:
    build: ./
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      APPROLE_ROLE_ID: db02de05-fa39-4855-059b-67221c5c2f63
      APPROLE_ROLE_NAME: app
    ports:
      - "8202:8200"