version: "3.8"

networks:
  elk:
    driver: bridge
    name: elk

volumes:
  postgres-data:

services:
  # postgres is a free and open-source relational database management
  # system emphasizing extensibility and SQL compliance.
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Tehran
    ports:
      - "5432:5432"
    networks:
      - elk
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
#  pgadmin:
#    container_name: pg_admin
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    depends_on:
#      postgres:
#        condition: service_healthy
#    ports:
#      - "8888:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    networks:
#      - elk
